/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.HotelSys;

/**
 *
 * @author rog91
 */
public class DisplayFrame extends javax.swing.JFrame {

    /**
     * Creates new form DisplayFrame
     */
    public DisplayFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbRoomTypes = new javax.swing.JComboBox<>();
        btnRemove = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        txtGuestName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        btnDispAll = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        kGradientPanel1.setEndColor(new java.awt.Color(181, 139, 139));
        kGradientPanel1.setGradientFocus(500);
        kGradientPanel1.setStartColor(new java.awt.Color(255, 167, 66));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Display Guest List");
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 202, 32);

        cmbRoomTypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard Room", "Suite Room", "King Suite Room", " " }));
        cmbRoomTypes.setBorder(null);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cmbRoomTypes, org.jdesktop.beansbinding.ELProperty.create("false"), cmbRoomTypes, org.jdesktop.beansbinding.BeanProperty.create("opaque"));
        bindingGroup.addBinding(binding);

        cmbRoomTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoomTypesActionPerformed(evt);
            }
        });
        kGradientPanel1.add(cmbRoomTypes);
        cmbRoomTypes.setBounds(50, 100, 123, 26);

        btnRemove.setText("Remove Guest");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnRemove, org.jdesktop.beansbinding.ELProperty.create("false"), btnRemove, org.jdesktop.beansbinding.BeanProperty.create("opaque"));
        bindingGroup.addBinding(binding);

        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnRemove);
        btnRemove.setBounds(510, 110, 112, 32);

        btnClose.setText("Close");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnClose, org.jdesktop.beansbinding.ELProperty.create("false"), btnClose, org.jdesktop.beansbinding.BeanProperty.create("opaque"));
        bindingGroup.addBinding(binding);

        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnClose);
        btnClose.setBounds(550, 20, 62, 32);

        txtGuestName.setBackground(new java.awt.Color(255, 255, 255));
        txtGuestName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtGuestName.setForeground(new java.awt.Color(0, 0, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, textArea, org.jdesktop.beansbinding.ELProperty.create("false"), txtGuestName, org.jdesktop.beansbinding.BeanProperty.create("opaque"));
        bindingGroup.addBinding(binding);

        kGradientPanel1.add(txtGuestName);
        txtGuestName.setBounds(290, 110, 200, 30);

        textArea.setBackground(new java.awt.Color(255, 255, 255));
        textArea.setColumns(20);
        textArea.setForeground(new java.awt.Color(0, 0, 0));
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        kGradientPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 160, 540, 260);

        btnDispAll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDispAll.setText("Display ALL");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnDispAll, org.jdesktop.beansbinding.ELProperty.create("false"), btnDispAll, org.jdesktop.beansbinding.BeanProperty.create("opaque"));
        bindingGroup.addBinding(binding);

        btnDispAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDispAllActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnDispAll);
        btnDispAll.setBounds(417, 20, 100, 32);

        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Enter a Guest Name to Remove");
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(310, 90, 180, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed

        dispose();

    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnDispAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDispAllActionPerformed
        // TODO add your handling code here:
        textArea.setText(HotelSys.display());
    }//GEN-LAST:event_btnDispAllActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        String name;
        name = txtGuestName.getText();

        if (HotelSys.removeGuest(name) == true) {
            textArea.setText("Guest is Removed");
        } else {
            textArea.setText("Guest not found!");
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void cmbRoomTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoomTypesActionPerformed
        // TODO add your handling code here:
        String roomType=cmbRoomTypes.getSelectedItem().toString();
        String output;
        output=HotelSys.searchGuest(roomType);
        
        textArea.setText(output);
       
    }//GEN-LAST:event_cmbRoomTypesActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDispAll;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cmbRoomTypes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField txtGuestName;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
