/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author rog91
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    StandardRoomFrame srf=new StandardRoomFrame();
    SuiteRoomFrame suit=new SuiteRoomFrame();
    KingSuiteRoom_Frame kng= new KingSuiteRoom_Frame();
    DisplayFrame df=new DisplayFrame();
   
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        btnSelect = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        radioStandard = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        radioSuite = new javax.swing.JRadioButton();
        radioKngSuite = new javax.swing.JRadioButton();
        btnDisplay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking App");

        kGradientPanel1.setEndColor(new java.awt.Color(0, 20, 56));
        kGradientPanel1.setGradientFocus(500);
        kGradientPanel1.setStartColor(new java.awt.Color(0, 226, 215));

        btnSelect.setText("Select");
        btnSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnSelect, org.jdesktop.beansbinding.ELProperty.create("false"), btnSelect, org.jdesktop.beansbinding.BeanProperty.create("opaque"));
        bindingGroup.addBinding(binding);

        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnSelect);
        btnSelect.setBounds(650, 410, 66, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Choose Your Room Type");
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(530, 120, 282, 32);

        radioStandard.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioStandard);
        radioStandard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioStandard.setForeground(new java.awt.Color(0, 0, 0));
        radioStandard.setText("Standard Room");
        radioStandard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, buttonGroup1, org.jdesktop.beansbinding.ELProperty.create("false"), radioStandard, org.jdesktop.beansbinding.BeanProperty.create("opaque"));
        bindingGroup.addBinding(binding);

        kGradientPanel1.add(radioStandard);
        radioStandard.setBounds(620, 200, 118, 28);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome To Booking App");
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(30, 30, 298, 32);

        radioSuite.setBackground(java.awt.Color.pink);
        buttonGroup1.add(radioSuite);
        radioSuite.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioSuite.setForeground(new java.awt.Color(0, 0, 0));
        radioSuite.setText("Suite Room");
        radioSuite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, buttonGroup1, org.jdesktop.beansbinding.ELProperty.create("false"), radioSuite, org.jdesktop.beansbinding.BeanProperty.create("opaque"));
        bindingGroup.addBinding(binding);

        kGradientPanel1.add(radioSuite);
        radioSuite.setBounds(620, 250, 97, 28);

        radioKngSuite.setBackground(new java.awt.Color(194, 161, 34));
        buttonGroup1.add(radioKngSuite);
        radioKngSuite.setForeground(new java.awt.Color(0, 0, 0));
        radioKngSuite.setText("King Suite Room");
        radioKngSuite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, buttonGroup1, org.jdesktop.beansbinding.ELProperty.create("false"), radioKngSuite, org.jdesktop.beansbinding.BeanProperty.create("opaque"));
        bindingGroup.addBinding(binding);

        kGradientPanel1.add(radioKngSuite);
        radioKngSuite.setBounds(620, 300, 125, 28);

        btnDisplay.setText("Display Guests");
        btnDisplay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnDisplay, org.jdesktop.beansbinding.ELProperty.create("false"), btnDisplay, org.jdesktop.beansbinding.BeanProperty.create("opaque"));
        bindingGroup.addBinding(binding);

        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnDisplay);
        btnDisplay.setBounds(680, 40, 114, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MainFrameIMG.png"))); // NOI18N
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(20, 130, 470, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        if(radioStandard.isSelected()==true)
        {
            srf.setVisible(true);
        }
        else if(radioSuite.isSelected()==true)
        {
            suit.setVisible(true);
        }
        else{
            kng.setVisible(true);
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        df.setVisible(true);
    }//GEN-LAST:event_btnDisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnSelect;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JRadioButton radioKngSuite;
    private javax.swing.JRadioButton radioStandard;
    private javax.swing.JRadioButton radioSuite;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
