/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.HotelSys;
import com.sun.glass.events.KeyEvent;

/**
 *
 * @author rog91
 */
public class SuiteRoomFrame extends javax.swing.JFrame {

    /**
     * Creates new form SuiteRoomFrame
     */
    public static String suinmonth;
    public static String suoutmonth;
    public SuiteRoomFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGuestName = new javax.swing.JTextField();
        txtCheckInDay = new javax.swing.JTextField();
        txtGuestNumber = new javax.swing.JTextField();
        txtCheckInMonth = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCheckOutDay = new javax.swing.JTextField();
        txtCheckOutMonth = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumOfBeds = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        messageBox = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        chkBreakfast = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        kGradientPanel1.setEndColor(new java.awt.Color(0, 85, 174));
        kGradientPanel1.setGradientFocus(500);
        kGradientPanel1.setStartColor(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Suite Room ");
        kGradientPanel1.add(jLabel7);
        jLabel7.setBounds(60, 30, 139, 32);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Name Surname");

        jLabel3.setText("Check-In Date");

        jLabel4.setText("Check-Out Date");

        jLabel5.setText("Guest Number");

        txtGuestName.setBackground(new java.awt.Color(255, 255, 255));
        txtGuestName.setForeground(new java.awt.Color(0, 0, 0));
        txtGuestName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));

        txtCheckInDay.setBackground(new java.awt.Color(255, 255, 255));
        txtCheckInDay.setForeground(new java.awt.Color(0, 0, 0));
        txtCheckInDay.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        txtCheckInDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckInDayActionPerformed(evt);
            }
        });

        txtGuestNumber.setBackground(new java.awt.Color(255, 255, 255));
        txtGuestNumber.setForeground(new java.awt.Color(0, 0, 0));
        txtGuestNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        txtGuestNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuestNumberActionPerformed(evt);
            }
        });

        txtCheckInMonth.setBackground(new java.awt.Color(255, 255, 255));
        txtCheckInMonth.setForeground(new java.awt.Color(0, 0, 0));
        txtCheckInMonth.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        txtCheckInMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckInMonthActionPerformed(evt);
            }
        });

        jLabel6.setText("Day");

        jLabel10.setText("Month");

        jLabel11.setText("2019");

        jLabel12.setText("Day");

        jLabel13.setText("Month");

        txtCheckOutDay.setBackground(new java.awt.Color(255, 255, 255));
        txtCheckOutDay.setForeground(new java.awt.Color(0, 0, 0));
        txtCheckOutDay.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        txtCheckOutDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckOutDayActionPerformed(evt);
            }
        });

        txtCheckOutMonth.setBackground(new java.awt.Color(255, 255, 255));
        txtCheckOutMonth.setForeground(new java.awt.Color(0, 0, 0));
        txtCheckOutMonth.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        txtCheckOutMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckOutMonthActionPerformed(evt);
            }
        });

        jLabel14.setText("2019");

        jLabel1.setText("Number of Beds");

        txtNumOfBeds.setBackground(new java.awt.Color(255, 255, 255));
        txtNumOfBeds.setForeground(new java.awt.Color(0, 0, 0));
        txtNumOfBeds.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        txtNumOfBeds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumOfBedsKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCheckInDay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCheckInMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCheckOutDay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCheckOutMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addComponent(txtNumOfBeds)
                    .addComponent(txtGuestNumber)
                    .addComponent(txtGuestName))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheckInMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txtCheckInDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCheckOutDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtCheckOutMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtGuestNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNumOfBeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );

        kGradientPanel1.add(jPanel2);
        jPanel2.setBounds(570, 60, 260, 370);

        btnAdd.setBackground(new java.awt.Color(25, 170, 166));
        btnAdd.setText("Book This Room");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnAdd, org.jdesktop.beansbinding.ELProperty.create("false"), btnAdd, org.jdesktop.beansbinding.BeanProperty.create("opaque"));
        bindingGroup.addBinding(binding);

        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        btnAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddKeyPressed(evt);
            }
        });
        kGradientPanel1.add(btnAdd);
        btnAdd.setBounds(570, 490, 122, 32);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SuiteRoomIMG.jpg"))); // NOI18N
        kGradientPanel1.add(jLabel8);
        jLabel8.setBounds(30, 90, 500, 340);

        messageBox.setBackground(new java.awt.Color(0, 0, 0));
        messageBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        messageBox.setForeground(new java.awt.Color(255, 51, 51));
        kGradientPanel1.add(messageBox);
        messageBox.setBounds(120, 500, 350, 30);

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnClear, org.jdesktop.beansbinding.ELProperty.create("false"), btnClear, org.jdesktop.beansbinding.BeanProperty.create("opaque"));
        bindingGroup.addBinding(binding);

        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnClear);
        btnClear.setBounds(720, 490, 65, 32);

        chkBreakfast.setText("Include Breakfast");
        kGradientPanel1.add(chkBreakfast);
        chkBreakfast.setBounds(570, 450, 140, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCheckInDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckInDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckInDayActionPerformed

    private void txtGuestNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuestNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuestNumberActionPerformed

    private void txtCheckInMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckInMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckInMonthActionPerformed

    private void txtCheckOutDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckOutDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckOutDayActionPerformed

    private void txtCheckOutMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckOutMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckOutMonthActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        double pricee=0.0;
        int checkOutday=Integer.parseInt(txtCheckOutDay.getText());
        int checkInday=Integer.parseInt(txtCheckInDay.getText());
        int checkOutMonth=Integer.parseInt(txtCheckOutMonth.getText());
        int checkInMonth=Integer.parseInt(txtCheckInMonth.getText());
        int numOfBeds=Integer.parseInt(txtNumOfBeds.getText());
        int guestNum=Integer.parseInt(txtGuestNumber.getText());
        
       if(checkOutMonth-checkInMonth==0)
        {
            pricee=(checkOutday-checkInday)*450; 
        }
        else if(checkOutMonth-checkInMonth > 0){
            pricee=((30*(checkOutMonth-checkInMonth))-(checkInday-checkOutday))*450;
        }
        
        if(numOfBeds>2 && guestNum >3){
            pricee+=100;
        }
        else if(guestNum>3 && numOfBeds>3){
            pricee+=200;}
        
        suinmonth=txtCheckInMonth.getText();
        suoutmonth=txtCheckOutMonth.getText();
        
        HotelSys.addSuiteRoom(numOfBeds, txtGuestName.getText(), checkInday , checkOutday, guestNum, pricee);
        
        messageBox.setText("A Room is Booked for You :)");
                    
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtCheckInDay.setText(null);
        txtCheckInMonth.setText(null);
        txtCheckOutDay.setText(null);
        txtCheckOutMonth.setText(null);
        txtGuestNumber.setText(null);
        txtNumOfBeds.setText(null);
        txtGuestName.setText(null);
        messageBox.setText(null);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnAddKeyPressed

    private void txtNumOfBedsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumOfBedsKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            double pricee=0.0;
        int checkOutday=Integer.parseInt(txtCheckOutDay.getText());
        int checkInday=Integer.parseInt(txtCheckInDay.getText());
        int checkOutMonth=Integer.parseInt(txtCheckOutMonth.getText());
        int checkInMonth=Integer.parseInt(txtCheckInMonth.getText());
        int numOfBeds=Integer.parseInt(txtNumOfBeds.getText());
        int guestNum=Integer.parseInt(txtGuestNumber.getText());
        
       if(checkOutMonth-checkInMonth==0)
        {
            pricee=(checkOutday-checkInday)*450; 
        }
        else if(checkOutMonth-checkInMonth > 0){
            pricee=((30*(checkOutMonth-checkInMonth))-(checkInday-checkOutday))*450;
        }
        
        if(numOfBeds>2 && guestNum >3){
            pricee+=100;
        }
        else if(guestNum>3 && numOfBeds>3){
            pricee+=200;}
        
        
          if(chkBreakfast.isSelected()==true)
        {
            pricee+=100;
        }
          
        suinmonth=txtCheckInMonth.getText();
        suoutmonth=txtCheckOutMonth.getText();
        
        HotelSys.addSuiteRoom(numOfBeds, txtGuestName.getText(), checkInday , checkOutday, guestNum, pricee);
        
        messageBox.setText("A Room is Booked for You :)");
                    
        }
            
    }//GEN-LAST:event_txtNumOfBedsKeyPressed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JCheckBox chkBreakfast;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel messageBox;
    private javax.swing.JTextField txtCheckInDay;
    private javax.swing.JTextField txtCheckInMonth;
    private javax.swing.JTextField txtCheckOutDay;
    private javax.swing.JTextField txtCheckOutMonth;
    private javax.swing.JTextField txtGuestName;
    private javax.swing.JTextField txtGuestNumber;
    private javax.swing.JTextField txtNumOfBeds;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
